-- 코드를 입력하세요
WITH BA AS (
SELECT B.BOOK_ID,
    B.CATEGORY,
    B.AUTHOR_ID,
    B.PRICE,
    A.AUTHOR_NAME
FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT BA.AUTHOR_ID,
BA.AUTHOR_NAME,
BA.CATEGORY,
SUM(BA.PRICE * S.SALES) AS 'TOTAL_SALES'
FROM BOOK_SALES S LEFT JOIN BA ON S.BOOK_ID = BA.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BA.AUTHOR_ID, BA.CATEGORY
ORDER BY BA.AUTHOR_ID ASC, BA.CATEGORY DESC