-- 코드를 입력하세요
SELECT ANIMAL_ID,
NAME
FROM (SELECT O.ANIMAL_ID,
      O.NAME,
      I.DATETIME AS 'I_DATETIME',
    O.DATETIME AS 'O_DATETIME'
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID) A
WHERE I_DATETIME IS NULL
ORDER BY ANIMAL_ID