-- 코드를 입력하세요
WITH H AS (SELECT FLAVOR,
SUM(TOTAL_ORDER) AS 'H_SUM'
FROM FIRST_HALF
GROUP BY FLAVOR),
J AS (SELECT FLAVOR,
SUM(TOTAL_ORDER) AS 'J_SUM'
FROM JULY
GROUP BY FLAVOR)

SELECT A.FLAVOR
FROM (SELECT H.FLAVOR,
H_SUM + J_SUM AS 'TOTAL_SUM'
FROM H LEFT JOIN J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR) A
ORDER BY A.TOTAL_SUM DESC
LIMIT 3