-- 코드를 입력하세요 
select USER_ID, NICKNAME, TOTAL_SALES
from 
(SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b LEFT JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
ORDER BY SUM(b.PRICE)) t
where TOTAL_SALES >= 700000