-- 코드를 입력하세요
SELECT P.MEMBER_NAME,
R.REVIEW_TEXT,
DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM REST_REVIEW R LEFT JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE P.MEMBER_ID IN (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (
    SELECT MAX(REVIEW_COUNT) 
    FROM (
        SELECT COUNT(MEMBER_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS SubQuery
))
ORDER BY 3, 2