WITH TOTAL_REVIEW AS (
    SELECT MEMBER_ID
            ,RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS REVIEW_RANK
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID)

SELECT PRO.MEMBER_NAME
        ,REV.REVIEW_TEXT
        ,DATE_FORMAT(REV.REVIEW_DATE,"%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE PRO
    INNER JOIN REST_REVIEW REV
    ON PRO.MEMBER_ID = REV.MEMBER_ID
WHERE REV.MEMBER_ID IN (SELECT MEMBER_ID
                        FROM TOTAL_REVIEW
                        WHERE REVIEW_RANK = 1)
ORDER BY REV.REVIEW_DATE, REV.REVIEW_TEXT