-- 코드를 입력하세요
SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR L ON L.CAR_ID = H.CAR_ID
WHERE L.CAR_TYPE = '세단' AND MONTH(H.START_DATE) = 10
ORDER BY 1 DESC